Create SelectionSorterTest
BME-MIT-IET/iet-hf2021-integracios-hf-csapat pull request #16
Opened 2021-05-11 12:17 UTC by burkodigergely

Create a unit test class for the algorithm named SelectionSorter

### Description

### Checklist

- [x] An issue was first created **before** opening this pull request
- [x] The new code follows the [contribution guidelines](CONTRIBUTING.md)
- [x] I have performed a self-review of my own code
- [x] I have commented my code, particularly in hard-to-understand areas
- [x] I have made corresponding changes to the documentation
- [x] My changes generate no new warnings
- [x] I have added tests to ensure that prove my fix is effective or that my feature works
- [x] New and existing unit tests pass locally with my changes

2021-05-11 13:56 UTC, AkosUzonyi requested changes

2021-05-11 13:56 UTC, AkosUzonyi commented on UnitTest/AlgorithmsTests/SelectionSorterTest.cs
> +}
The comparer class should be a separate class (eg `PersonComparer`).

2021-05-11 14:38 UTC, yorickramer approved these changes
Alig volt olyan
Anno, aki hitt bennem, de komolyan
Befutottam, de nem értik, hogy hogyan
Mégis gratulálnak nekem sokan
-- T. Gabby

Ezúttal én is szeretnék neked gratulálni a szép munkádhoz.

2021-05-14 19:43 UTC, AkosUzonyi approved these changes
Thanks for the fix, looks perfect now :).

2021-05-15 17:24 UTC, merged