Partial code coverage fix
BME-MIT-IET/iet-hf2021-integracios-hf-csapat pull request #2
Opened 2021-04-30 18:58 UTC by gyupetosz

100% code coverage achieved on PrimeHashing family class.

2021-04-30 20:11 UTC, AkosUzonyi requested changes

2021-04-30 20:11 UTC, AkosUzonyi commented on UnitTest/DataStructuresTests/HashTableSeparateChainingTest.cs
> +}
Please remove every change not related to the new unit test

2021-04-30 20:11 UTC, AkosUzonyi commented on UnitTest/DataStructuresTests/PrimeHashingFamilyTest.cs
> +            PrimeHashingFamily hash2 = new PrimeHashingFamily(1);
We could test with a bit larger number of hash functions than 1.

2021-04-30 20:11 UTC, AkosUzonyi commented on UnitTest/DataStructuresTests/PrimeHashingFamilyTest.cs
> +                hash2 = new PrimeHashingFamily(i);
These assignments shouldn't be here, hash1 and hash2 are already initialized.

2021-04-30 20:11 UTC, AkosUzonyi commented on UnitTest/DataStructuresTests/PrimeHashingFamilyTest.cs
> +            int hashValue = "főzelék".GetHashCode();
Hami :D

2021-04-30 20:11 UTC, AkosUzonyi commented on UnitTest/DataStructuresTests/PrimeHashingFamilyTest.cs
> +                hash2 = new PrimeHashingFamily(i);
Likewise

2021-05-01 08:39 UTC, MarcellHarmaci requested changes

2021-05-01 08:39 UTC, MarcellHarmaci commented on UnitTest/DataStructuresTests/PrimeHashingFamilyTest.cs
> +                hash1 = new PrimeHashingFamily(i);
This is changing the condition of the for loop inside the loop, which is a bad practice.

2021-05-03 09:58 UTC, AkosUzonyi approved these changes

2021-05-03 13:21 UTC, AkosUzonyi requested changes
Please add a short documentation of this change to `doc/unit_test.md`

2021-05-09 17:50 UTC, MarcellHarmaci approved these changes

2021-05-11 14:14 UTC, merged